# Build settings
markdown: kramdown

# Don't add these files to the site.
exclude:
- Gemfile
- Gemfile.lock
- run_jekyll.sh

# Set collections
# https://jekyllrb.com/docs/collections/
collections:
  projects:
    output: true

# Set defaults for projects collection
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: projects
